### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by machulong** [l-yohai/lotto#1]
hello,thank you for your sharing，could you get the data from csv

**Comment by l-yohai** [comment]
You can get the data from [data/lotto_numbers](https://github.com/l-yohai/lotto/blob/main/data/lotto_numbers.jsonl)

If you want to convert to csv, you can try it as below.

```
import pandas as pd

df = pd.read_json("data/lotto_numbers.jsonl", lines=True)
df.to_csv("SAVE_PATH")
```

**Comment by machulong** [comment]
thanks!
